@startuml
hide empty description
[*] --> メインメニュー

state メインメニュー  {
    メインメニュー : パラメータ新規作成
    メインメニュー : パラメータ変更
    メインメニュー : ユーティリティ
}

メインメニュー --> 空レコード生成 : [パラメータ新規作成]選択
メインメニュー --> DBから対象レコードSELECT : [パラメータ変更]選択\npkg_nameを用いて\n\
対象を指定する
空レコード生成 --> 変更
DBから対象レコードSELECT --> 変更
メインメニュー --> ユーティリティ : [ユーティリティ]選択
ユーティリティ --> メインメニュー : 戻る
ユーティリティ --> 機台情報変更 : [M304機台登録変更]選択\n登録の時にはMACアドレスを入力\n\
変更のときの対象選択には\nMACアドレスを指定
機台情報変更 --> ユーティリティ : 中断
機台情報変更 --> 機台情報更新 : [変更&終了]
機台情報更新 --> ユーティリティ
機台情報変更 --> 機台情報保存 : [保存&終了]
機台情報保存 --> ユーティリティ

変更 --> メインメニュー : 中断
変更 --> 更新 : 更新&終了
更新 --> メインメニュー
変更 --> 保存 : 保存&終了
保存 --> メインメニュー

state ユーティリティ {
    ユーティリティ : データ削除
    ユーティリティ : pkg_name変更
    ユーティリティ : 別名編集
    ユーティリティ : M304機台登録変更
    ユーティリティ : M304機台削除
    ユーティリティ : M304へ転送
    ユーティリティ : M304から転送
}

state 変更 {
    変更 : blk_b : RLY control sequence data
    変更 : blk_c : compare CCMTYPE define
    変更 : blk_d : sending data
}
変更 --> 変更 : [編集]

state 機台情報変更 {
    機台情報変更 : blk_a : 機台固有情報の変更
}
機台情報変更 --> 機台情報変更 : [編集]

@enduml